import jsPDF from "jspdf";
import type { AppChartData } from "../types/chart";
import type { ChartCustomization } from "../types/chart";

function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export async function exportChartToPdf(
  canvasElement: HTMLCanvasElement,
  chartData: AppChartData,
  customization: ChartCustomization,
  filename?: string
): Promise<void> {
  const pdf = new jsPDF({ orientation: "landscape", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  const H = pdf.internal.pageSize.getHeight();
  const now = new Date().toLocaleDateString();

  // Header bar
  pdf.setFillColor(99, 102, 241);
  pdf.rect(0, 0, W, 12, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.text("ChartMaker", 8, 8);
  pdf.text(now, W - 8, 8, { align: "right" });

  // Title
  let y = 20;
  if (customization.title) {
    pdf.setTextColor(30, 30, 30);
    pdf.setFontSize(16);
    pdf.text(customization.title, W / 2, y, { align: "center" });
    y += 8;
  }

  // Chart image
  const imgData = canvasElement.toDataURL("image/png");
  const chartH = 110;
  pdf.addImage(imgData, "PNG", 10, y, W - 20, chartH);
  y += chartH + 8;

  // Data table
  const labels = (chartData.labels ?? []).map(String);
  const dsLabels = chartData.datasets.map(ds => String(ds.label ?? ""));
  const colWidth = Math.min(40, (W - 20) / (dsLabels.length + 1));
  const rowH = 7;

  // Table header
  pdf.setFillColor(240, 242, 255);
  pdf.rect(10, y, W - 20, rowH, "F");
  pdf.setTextColor(50, 50, 150);
  pdf.setFontSize(8);
  pdf.text("Label", 12, y + 5);
  dsLabels.forEach((lbl, i) => pdf.text(lbl, 12 + colWidth * (i + 1), y + 5));
  y += rowH;

  // Table rows (max 20)
  pdf.setTextColor(40, 40, 40);
  const maxRows = Math.min(labels.length, 20);
  for (let i = 0; i < maxRows; i++) {
    if (i % 2 === 0) {
      pdf.setFillColor(248, 249, 255);
      pdf.rect(10, y, W - 20, rowH, "F");
    }
    pdf.text(labels[i], 12, y + 5);
    chartData.datasets.forEach((ds, di) => {
      const val = (ds.data as number[])[i];
      pdf.text(String(val ?? ""), 12 + colWidth * (di + 1), y + 5);
    });
    y += rowH;
    if (y > H - 15) break;
  }

  // Footer
  pdf.setDrawColor(200, 200, 200);
  pdf.line(10, H - 10, W - 10, H - 10);
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(7);
  pdf.text("Generated by ChartMaker", W / 2, H - 5, { align: "center" });

  const fname = filename
    || (customization.title ? slug(customization.title) : `chartmaker-${Date.now()}`);
  pdf.save(`${fname}.pdf`);
}
